"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import Api from "@/utils/api/api";

export default function EmailAuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const isSignup = mode === "signup";
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setSaving(true); try { const result = await Api.post(isSignup ? "/user/" : "/user/login", { email, password }); if (!result.ok) throw new Error(result.detail || "Unable to continue"); const login = isSignup ? await Api.post("/user/login", { email, password }) : result; if (!login.ok || !login.access_token) throw new Error(login.detail || "No session was returned"); localStorage.setItem("token", login.access_token); router.replace("/"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to continue"); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-surface-primary p-6 md:p-12"><section className="mx-auto max-w-md rounded-lg border border-outline-variant bg-surface-container-lowest p-6"><Link href="/" className="text-sm text-brand-primary">← Strategies</Link><h1 className="mt-5 text-3xl font-bold">{isSignup ? "Create your account" : "Log in"}</h1><p className="mt-2 text-on-surface-variant">Use your email and password to keep your strategy records across browsers.</p><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Email<input className="mt-1 w-full rounded border border-outline-variant p-2" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="block text-sm font-medium">Password<input className="mt-1 w-full rounded border border-outline-variant p-2" type="password" autoComplete={isSignup ? "new-password" : "current-password"} minLength={isSignup ? 8 : 1} required value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="text-sm text-red-700">{error}</p>}<button className="w-full rounded bg-brand-primary px-4 py-2 font-medium text-white disabled:opacity-50" disabled={saving}>{saving ? "Please wait…" : isSignup ? "Create account" : "Log in"}</button></form><p className="mt-5 text-sm text-on-surface-variant">{isSignup ? "Already have an account?" : "New here?"} <Link className="text-brand-primary" href={isSignup ? "/login" : "/signup"}>{isSignup ? "Log in" : "Create an account"}</Link></p></section></main>;
}
