"""Static NSE sector constituent snapshot used by this standalone study."""

def tickers(value: str) -> list[str]:
    return [f"{ticker}.NS" for ticker in value.split()]


SECTOR_STOCKS = {
    "Nifty IT": tickers("COFORGE HCLTECH INFY LTM MPHASIS OFSS PERSISTENT TCS TECHM WIPRO"),
    "Nifty Bank": tickers("AUBANK AXISBANK BANKBARODA CANBK FEDERALBNK HDFCBANK ICICIBANK IDFCFIRSTB INDUSINDBK KOTAKBANK PNB SBIN UNIONBANK YESBANK"),
    "Nifty Auto": tickers("ASHOKLEY BAJAJ-AUTO BHARATFORG BOSCHLTD EICHERMOT EXIDEIND HEROMOTOCO M&M MARUTI MOTHERSON SONACOMS TVSMOTOR TMPV TIINDIA UNOMINDA"),
    "Nifty FMCG": tickers("BRITANNIA COLPAL DABUR EMAMILTD GODREJCP HINDUNILVR ITC MARICO NESTLEIND PATANJALI RADICO TATACONSUM UBL UNITDSPR VBL"),
    "Nifty Pharma": tickers("ABBOTINDIA AJANTPHARM ALKEM AUROPHARMA BIOCON CIPLA DIVISLAB DRREDDY GLAND GLENMARK IPCALAB LAURUSLABS LUPIN MANKIND PPLPHARMA SAILIFE SUNPHARMA TORNTPHARM WOCKPHARMA ZYDUSLIFE"),
    "Nifty Metal": tickers("APLAPOLLO ADANIENT HINDALCO HINDCOPPER HINDZINC JSWSTEEL JSL JINDALSTEL LLOYDSME NMDC NATIONALUM SAIL TATASTEEL VEDL WELCORP"),
    "Nifty Realty": tickers("ABREL ANANTRAJ BRIGADE DLF GODREJPROP LODHA OBEROIRLTY PHOENIXLTD PRESTIGE SOBHA"),
    "Nifty Energy": tickers("ABB ADANIENSOL ADANIGREEN ADANIPOWER ATGL AEGISLOG BHEL BPCL CESC CGPOWER CASTROLIND COALINDIA GAIL GVT&D HINDPETRO POWERINDIA IOC IGL INOXWIND JSWENERGY JPPOWER MGL NHPC NLCINDIA NTPCGREEN NTPC NAVA ONGC OIL PETRONET POWERGRID RELIANCE RPOWER SJVN ENRIN SIEMENS SUZLON TATAPOWER THERMAX TORNTPOWER"),
    "Nifty Financial Services": tickers("AXISBANK BSE BAJFINANCE BAJAJFINSV CHOLAFIN HDFCBANK HDFCLIFE ICICIBANK ICICIGI JIOFIN KOTAKBANK LICHSGFIN MFSL MUTHOOTFIN PFC RECLTD SBICARD SBILIFE SHRIRAMFIN SBIN"),
    "Nifty Media": tickers("DBCORP HATHWAY NAZARA NETWORK18 PVRINOX PFOCUS SAREGAMA SUNTV TIPSMUSIC ZEEL"),
}


def stock_universe() -> dict[str, str]:
    """Map each unique ticker to sector memberships without double counting it."""
    memberships: dict[str, list[str]] = {}
    for sector, symbols in SECTOR_STOCKS.items():
        for ticker in symbols:
            memberships.setdefault(ticker, []).append(sector)
    return {ticker: " | ".join(sectors) for ticker, sectors in sorted(memberships.items())}
