"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import Api from "@/utils/api/api";
type Instrument = {ticker:string; name:string; instrument_type:string; seasonal_return:number; alpha:number; beta:number};
type Plan = {plan_id:number; sector:string; entry_date:string; exit_date:string; window_days:number; oos_mean_return:number; oos_win_rate:number; oos_worst_return:number; oos_worst_drawdown:number; stock?:Instrument; etf?:Instrument};
type Headline = {title:string; url:string; published_at?:string};
type LiveInstrument = {ticker:string; name:string; instrument_type:string; seasonal_return?:number; alpha?:number; beta?:number; observation_count?:number; years?:{year:number;entry_date:string;exit_date:string;return:number}[]; eligible:boolean; reason?:string};
const pct = (value: number) => `${(value * 100).toFixed(2)}%`;
export default function PlanDetail({ params }: { params: Promise<{id:string}> }) {
  const [plan, setPlan] = useState<Plan>(); const [news, setNews] = useState<Headline[]>([]); const [instruments, setInstruments] = useState<LiveInstrument[]>([]); const [instrumentLoading, setInstrumentLoading] = useState(true);
  useEffect(() => { params.then(({id}) => { Api.get(`/anomaly/plans/${id}`).then((result) => setPlan(result as unknown as Plan)); Api.get(`/anomaly/plans/${id}/headlines`).then((result) => setNews(Array.isArray(result) ? result as Headline[] : [])); Api.get(`/anomaly/plans/${id}/instruments`).then((result) => setInstruments(Array.isArray(result.instruments) ? result.instruments : [])).finally(() => setInstrumentLoading(false)); }); }, [params]);
  if (!plan) return <main className="p-8">Loading plan…</main>;
  return <main className="min-h-screen bg-surface-primary p-6 md:p-12"><div className="mx-auto max-w-6xl"><Link href="/seasonal-research" className="text-sm text-brand-primary">← Market-window calendar</Link><h1 className="mt-5 text-3xl font-bold">{plan.sector}</h1><p className="mt-1 text-on-surface-variant">Enter at close on {plan.entry_date}; exit at close on {plan.exit_date} ({plan.window_days} trading days).</p><section className="mt-8 grid gap-4 md:grid-cols-2"><Evidence plan={plan}/><Investments plan={plan}/></section><LiveInstruments loading={instrumentLoading} instruments={instruments}/><section className="mt-8 rounded-lg border border-outline-variant bg-surface-container-lowest p-5"><h2 className="text-xl font-semibold">Recent headlines</h2>{news.length ? <ul className="mt-3 space-y-3">{news.map((item) => <li key={item.url}><a className="text-brand-primary underline" href={item.url} target="_blank" rel="noreferrer">{item.title}</a><p className="text-xs text-on-surface-variant">{item.published_at}</p></li>)}</ul> : <p className="mt-2 text-on-surface-variant">No headlines are available right now.</p>}</section><p className="mt-8 text-sm text-on-surface-variant">Research only. Instrument data is fetched from Yahoo Finance when this page opens; historical performance, alpha, beta, and headlines do not guarantee future results.</p></div></main>;
}
function Evidence({plan}:{plan:Plan}) { return <section className="rounded-lg border border-outline-variant bg-surface-container-lowest p-5"><h2 className="text-xl font-semibold">Walk-forward evidence</h2>{[["OOS average",pct(plan.oos_mean_return)],["OOS win rate",pct(plan.oos_win_rate)],["Worst return",pct(plan.oos_worst_return)],["Worst drawdown",pct(plan.oos_worst_drawdown)]].map(([a,b])=><div className="mt-3 flex justify-between" key={a}><span className="text-on-surface-variant">{a}</span><b>{b}</b></div>)}</section>; }
function Investments({plan}:{plan:Plan}) { return <section className="rounded-lg border border-outline-variant bg-surface-container-lowest p-5"><h2 className="text-xl font-semibold">Investable instruments</h2>{[plan.stock,plan.etf].map((item, i) => <div className="mt-4" key={i}>{item ? <><b>{item.instrument_type}: {item.name} ({item.ticker})</b><p className="text-sm text-on-surface-variant">Seasonal return {pct(item.seasonal_return)} · alpha {pct(item.alpha)} · beta {item.beta.toFixed(2)}</p></> : <p className="text-on-surface-variant">No qualifying {i ? "ETF" : "stock"} is mapped.</p>}</div>)}</section>; }
function LiveInstruments({loading, instruments}:{loading:boolean; instruments:LiveInstrument[]}) {
  const [sort, setSort] = useState<"return"|"alpha"|"beta"|"ticker">("return");
  const value = (item:LiveInstrument) => sort === "return" ? item.seasonal_return ?? -Infinity : sort === "alpha" ? item.alpha ?? -Infinity : item.beta ?? -Infinity;
  const ordered = useMemo(() => [...instruments].sort((a,b) => sort === "ticker" ? a.ticker.localeCompare(b.ticker) : value(b) - value(a)), [instruments, sort]);
  return <section className="mt-8 rounded-lg border border-outline-variant bg-surface-container-lowest p-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Mapped stocks and ETFs</h2><p className="text-sm text-on-surface-variant">Live Yahoo Finance calculation. Scroll horizontally to view every metric.</p></div><label className="whitespace-nowrap text-sm">Sort <select className="ml-2 rounded border border-outline-variant bg-white px-2 py-1" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="return">Seasonal return</option><option value="alpha">Alpha</option><option value="beta">Beta</option><option value="ticker">Ticker</option></select></label></div>
    {loading ? <p className="mt-4" role="status">Loading live instrument data…</p> : <div className="mt-4 overflow-x-auto rounded-md border border-outline-variant"><table className="min-w-[1120px] w-full table-fixed text-sm"><thead className="bg-surface-container-low text-left text-xs uppercase tracking-wide text-on-surface-variant"><tr><th className="w-40 px-4 py-3">Instrument</th><th className="w-20 px-3 py-3">Type</th><th className="w-28 px-3 py-3 text-right">Return</th><th className="w-24 px-3 py-3 text-right">Alpha</th><th className="w-20 px-3 py-3 text-right">Beta</th><th className="w-[360px] px-4 py-3">Five seasonal returns</th><th className="w-64 px-4 py-3">Status</th></tr></thead><tbody>{ordered.map(item=><tr className="border-t border-outline-variant align-top" key={item.ticker}><td className="px-4 py-3 font-medium">{item.name}<br/><span className="text-xs font-normal text-on-surface-variant">{item.ticker}</span></td><td className="px-3 py-3">{item.instrument_type}</td><td className="px-3 py-3 text-right tabular-nums">{item.seasonal_return == null ? "—" : pct(item.seasonal_return)}</td><td className="px-3 py-3 text-right tabular-nums">{item.alpha == null ? "—" : pct(item.alpha)}</td><td className="px-3 py-3 text-right tabular-nums">{item.beta == null ? "—" : item.beta.toFixed(2)}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1.5">{item.years?.map(year=><span className="rounded bg-surface-container-low px-2 py-1 text-xs tabular-nums" key={year.year}>{year.year} {pct(year.return)}</span>) ?? "—"}</div></td><td className="px-4 py-3 text-xs leading-5">{item.eligible ? <span className="rounded bg-green-100 px-2 py-1 font-medium text-green-800">Eligible</span> : item.reason}</td></tr>)}</tbody></table></div>}
  </section>;
}
